sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.10'
before_script:
  - npm prune
  - gcc --version
  - g++ --version
after_success:
  - npm run semantic-release
